#!/usr/bin/env bash

NAME="DiscImage"
CODENAME="discimage"
COPYRIGHT="Copyright (C) 2007 Nathan Shearer"
LICENSE="GNU General Public License 2.0"
VERSION="2.0.0.0"

# \brief Ensures dependencies are present
# \param $@ The dependencies to check for
function discimage_check_dependencies
{
	for TOOL in "$@"; do
		if ! type "$TOOL" >/dev/null 2>/dev/null; then
			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
			exit
		fi
	done
}

# \brief Creates a cdrdao image (Mode 1 Raw) from a cdrom disc
# \param $1 The source device
# \param $2 The basename of the output image
function discimage_cdrom_mode1raw
{
	local DEVICE="$1"
	local BASENAME="$2"
	echo 1 | cdrdao read-cd --device "$DEVICE" --driver generic-mmc:0x20000 --datafile "$BASENAME".bin --read-raw -v 2 "$BASENAME".toc 2>&1 | tee "$BASENAME.log"
	toc2cue "$BASENAME.toc" "$BASENAME.cue"
	md5sum "$BASENAME.bin" "$BASENAME.cue" "$BASENAME.toc" > "$BASENAME.md5"
	pure-sfv -c -s "$BASENAME.sfv" -f "$BASENAME.bin" "$BASENAME.cue" "$BASENAME.toc"
}

# \brief Creates a cdrdao image (Mode 1 Raw with Subchannels) from a cdrom disc
# \param $1 The source device
# \param $2 The basename of the output image
function discimage_cdrom_mode1rawsub
{
	local DEVICE="$1"
	local BASENAME="$2"
	echo 1 | cdrdao read-cd --device "$DEVICE" --driver generic-mmc:0x20000 --datafile "$BASENAME".bin --read-raw --read-subchan rw_raw -v 2 "$BASENAME".toc 2>&1 | tee "$BASENAME.log"
	toc2cue "$BASENAME.toc" "$BASENAME.cue"
	md5sum "$BASENAME.bin" "$BASENAME.cue" "$BASENAME.toc" > "$BASENAME.md5"
	pure-sfv -c -s "$BASENAME.sfv" -f "$BASENAME.bin" "$BASENAME.cue" "$BASENAME.toc"
}

# \brief Creates an image from a dvdrom disc
# \param $1 The source device
# \param $2 The basename of the output image
function discimage_dvdrom
{
	local DEVICE="$1"
	local BASENAME="$2"
	mplayer -dvd-device "$DEVICE" dvd:// -frames 64 -msglevel identify=6 1>/dev/null 2>/dev/null
	ddrescue "$DEVICE" "$BASENAME.iso" "$BASENAME.log"
	md5sum "$BASENAME.iso" > "$BASENAME.md5"
	pure-sfv -c -s "$BASENAME.sfv" -f "$BASENAME.iso"
}

# \brief Creates an image from a floppy disc
# \param $1 The source device
# \param $2 The basename of the output image
function discimage_floppy
{
	local DEVICE="$1"
	local BASENAME="$2"
	ddrescue "$DEVICE" "$BASENAME.bin" "$BASENAME.log"
	md5sum "$BASENAME.bin" > "$BASENAME.md5"
	pure-sfv -c -s "$BASENAME.sfv" -f "$BASENAME.bin"
}

# \brief Displays the help and exits the program
function discimage_help
{
	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
	echo "Description:"
	echo "  Create an image of a removable disc."
	echo
	echo "Usage:"
	echo "  $CODENAME [options] -t <type> -o <basename>"
	echo
	echo "Options:"
	echo "  -h, --help"
	echo "    Display this help message and exit."
	echo "  -i, --input /dev/sr0"
	echo "    Input device."
	echo "  -o, --output basename"
	echo "    Output basename."
	echo "  -t, --type type"
	echo "    Specify the type of disc image to create. Supported types are:"
	echo "      floppy"
	echo "        An binary image with 512 byte sectors"
	echo "      cdrom-mode1raw"
	echo "        A cdrdao bin+cue+toc image."
	echo "        2352 Byte CD-ROM Mode 1 Raw Sector Format:"
	echo "          12 Bytes (Sync Pattern)"
	echo "          3 Bytes (Address)"
	echo "          1 Bytes (Mode, 0x01)"
	echo "          2048 Bytes (Data)"
	echo "          4 Bytes (Error Detection)"
	echo "          8 Bytes (Reserved, 0x0000000000000000)"
	echo "          276 Bytes (Error Correction)"
	echo "      cdrom-mode1rawsub"
	echo "        A cdrdao bin+cue+toc image."
	echo "        2448 Byte CD-ROM Mode 1 Raw with Subchannels Sector Format:"
	echo "          12 Bytes (Sync Pattern)"
	echo "          3 Bytes (Address)"
	echo "          1 Bytes (Mode, 0x01)"
	echo "          2048 Bytes (Data)"
	echo "          4 Bytes (Error Detection)"
	echo "          8 Bytes (Reserved, 0x0000000000000000)"
	echo "          276 Bytes (Error Correction)"
	echo "          96 Bytes (Subcannels)"
	echo "      dvdrom"
	echo "        An iso image with 2048 byte sectors"
	echo
	echo "Examples:"
	echo "  $CODENAME -i /dev/sr0 -t cdrom-mode1rawsub -o disc1"
	echo "  $CODENAME -i /dev/sr0 -t dvdrom -o S1D1"
	echo
	echo "Version:"
	echo "  $NAME $VERSION"
	echo "  $COPYRIGHT"
	echo "  Licensed under $LICENSE"
	exit
}

# \brief The main function of this script
function discimage_main
{
	case "$TYPE" in
		"cdrom-mode1raw") discimage_cdrom_mode1raw "$INPUT" "$OUTPUT";;
		"cdrom-mode1rawsub") discimage_cdrom_mode1rawsub "$INPUT" "$OUTPUT";;
		"dvdrom") discimage_dvdrom "$INPUT" "$OUTPUT";;
		"floppy") discimage_floppy "$INPUT" "$OUTPUT";;
		*) echo "Unknown disc type: $TYPE";;
	esac
}

#------------------------------------------------------------------------------
# default configuration

INPUT=/dev/sr0

#------------------------------------------------------------------------------
# config files

if [ -r /etc/$CODENAME/$CODENAME.conf ]; then
	. /etc/$CODENAME/$CODENAME.conf
fi
if [ -r ~/.$CODENAME.conf ]; then
	. ~/.$CODENAME.conf
fi

#------------------------------------------------------------------------------
# command line arguments

if [ $# -eq 0 ]; then
	discimage_help
fi
while [ $# -ne 0 ]; do
	case "$1" in
		"-h"|"--help")
			discimage_help
			exit
			;;
		"-i"|"--input")
			INPUT="$2"
			shift 2
			;;
		"-o"|"--output")
			OUTPUT="$2"
			shift 2
			;;
		"-t"|"--type")
			TYPE="$2"
			shift 2
			;;
		*)
			discimage_help
			exit
			;;
	esac
done
if [ "$OUTPUT" = "" ]; then
	echo "error: An output basename must be provided."
	exit 1
fi

#------------------------------------------------------------------------------
# prepare environment

discimage_check_dependencies cdrdao ddrescue md5sum toc2cue pure-sfv

#------------------------------------------------------------------------------
# begin execution

discimage_main
